---
- name: install libssl
  apt:
    name: libssl1.1:i386
    state: present
  become: yes

- name: create libcrypto symlink
  file:
    src: /lib/i386-linux-gnu/libcrypt.so.1
    dest: /usr/lib/libcrypto.so.4
    state: link
  become: yes

- name: prevent excesscoll iol error
  sysctl:
    name: net.unix.max_dgram_qlen
    value: '10000'
    state: present
  become: yes

- name: block phone home
  lineinfile:
    path: /etc/hosts
    insertafter: '^127\.0\.1\.1'
    line: "127.0.0.84\txml.cisco.com"
    state: present
  become: yes

- name: create demo iol license file
  script: create_demo_iol_lic.py
  args:
    chdir: /opt/gns3
    executable: python3
    creates: /opt/gns3/iourc
  become: yes

- name: change file ownership for demo iol license file
  file:
    path: /opt/gns3/iourc
    owner: gns3
    group: gns3
  become: yes
...